# Additive production function

Hildreth (1954) was the first to consider nonparametric regression subject to monotonicity and concavity constraints in the case of a single input variable $x$. Kuosmanen (2008) extended Hildreth’s approach to the multivariate setting with a vector-valued $\bf{x}$, and coined the term convex nonparametric least squares (`CNLS`) for this method. `CNLS` builds upon the assumption that the true but unknown production function $f$ belongs to the set of continuous, monotonic increasing and globally concave functions, imposing exactly the same production axioms as standard DEA. 

The multivariate `CNLS` formulation is defined as:

\begin{align*}
& \underset{\alpha, \beta, \varepsilon} {min} \sum_{i=1}^n\varepsilon_i^2 \\
& \text{s.t.} \\
&  y_i = \alpha_i + \beta_i^{'}X_i + \varepsilon_i \quad \forall i \\
&  \alpha_i + \beta_i^{'}X_i \le \alpha_j + \beta_j^{'}X_i  \quad  \forall i, j\\
&  \beta_i \ge 0 \quad  \forall i \\
\end{align*}

where $\alpha_i$ and $\beta_i$ define the intercept and slope parameters of tangent hyperplanes that characterize the estimated piece-wise linear frontier. $\varepsilon_i$ denotes the CNLS residuals. The first constraint can be interpreted as a multivariate regression equation, the second constraint imposes convexity, and the third constraint imposes monotonicity.

In [1]:
# import packages
from pystoned import CNLS
import pandas as pd
import numpy as np

In [2]:
# import Finnish electricity distribution firms data
url = 'https://raw.githubusercontent.com/ds2010/pyStoNED/master/sources/data/firms.csv'
df = pd.read_csv(url, error_bad_lines=False)
df.head(5)

OPEX  CAPEX  TOTEX  Energy  Length  Customers  PerUndGr
0   681    729   1612      75     878       4933      0.11
1   559    673   1659      62     964       6149      0.21
2   836    851   1708      78     676       6098      0.75
3  7559   8384  18918     683   12522      55226      0.13
4   424    562   1167      27     697       1670      0.03

In [3]:
# output
y = df['Energy']

# inputs
x1 = df['OPEX']
x1 = np.asmatrix(x1).T
x2 = df['CAPEX']
x2 = np.asmatrix(x2).T
x = np.concatenate((x1, x2), axis=1)

In [4]:
# define and solve the CNLS model
model = CNLS.CNLS(y, x, z=None, cet = "addi", fun = "prod", rts = "vrs")
model.optimize(remote=False)

Estimating the additive model locally with mosek solver
Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : QO (quadratic optimization problem)
  Constraints            : 7921            
  Cones                  : 0               
  Scalar variables       : 445             
  Matrix variables       : 0               
  Integer variables      : 0               

Optimizer started.
Quadratic to conic reformulation started.
Quadratic to conic reformulation terminated. Time: 0.03    
Presolve started.
Linear dependency checker started.
Linear dependency checker terminated.
Eliminator started.
Freed constraints in eliminator : 89
Eliminator terminated.
Eliminator started.
Freed constraints in eliminator : 0
Eliminator terminated.
Eliminator - tries                  : 2                 time                   : 0.00            
Lin. dep.  - tries                  : 1                 time                   : 0.00          

In [5]:
# display the alpha
model.display_alpha()

alpha : alpha
    Size=89, Index=I
    Key : Lower : Value               : Upper : Fixed : Stale : Domain
      0 :  None : -22.935939927355427 :  None : False : False :  Reals
      1 :  None :  -22.98683384275405 :  None : False : False :  Reals
      2 :  None : -22.863887348352677 :  None : False : False :  Reals
      3 :  None :   33.46099118865206 :  None : False : False :  Reals
      4 :  None : -22.938469349203928 :  None : False : False :  Reals
      5 :  None :  -17.75385608884956 :  None : False : False :  Reals
      6 :  None : -22.920879709464177 :  None : False : False :  Reals
      7 :  None : -17.794865135550058 :  None : False : False :  Reals
      8 :  None : -22.903309377941486 :  None : False : False :  Reals
      9 :  None : -17.870824583422213 :  None : False : False :  Reals
     10 :  None :   89.08424852664143 :  None : False : False :  Reals
     11 :  None :    90.8645383815144 :  None : False : False :  Reals
     12 :  None : -22.835135090317333 :  N

In [6]:
# display the beta
model.display_beta()

beta : beta
    Size=178, Index=beta_index
    Key     : Lower : Value                  : Upper : Fixed : Stale : Domain
     (0, 0) :   0.0 :    0.13585845731547977 :  None : False : False :  Reals
     (0, 1) :   0.0 :   0.011273984231181894 :  None : False : False :  Reals
     (1, 0) :   0.0 :    0.13637662344803758 :  None : False : False :  Reals
     (1, 1) :   0.0 :   0.010903786808952633 :  None : False : False :  Reals
     (2, 0) :   0.0 :    0.13566698257247733 :  None : False : False :  Reals
     (2, 1) :   0.0 :   0.011363143137967071 :  None : False : False :  Reals
     (3, 0) :   0.0 :    0.13235213743268964 :  None : False : False :  Reals
     (3, 1) :   0.0 : 2.1117206207915625e-08 :  None : False : False :  Reals
     (4, 0) :   0.0 :    0.14755558448025402 :  None : False : False :  Reals
     (4, 1) :   0.0 :  0.0019124581256673425 :  None : False : False :  Reals
     (5, 0) :   0.0 :     0.1341072373561363 :  None : False : False :  Reals
     (5, 1) :   0.0 :

In [7]:
# display the residual
model.display_residual()

epsilon : residual
    Size=89, Index=I
    Key : Lower : Value               : Upper : Fixed : Stale : Domain
      0 :  None : -2.8024040090178914 :  None : False : False :  Reals
      1 :  None :  1.4140528128759229 :  None : False : False :  Reals
      2 :  None : -22.223744892648355 :  None : False : False :  Reals
      3 :  None :    -350.91097508901 :  None : False : False :  Reals
      4 :  None : -13.699899937048826 :  None : False : False :  Reals
      5 :  None :  101.01484316190096 :  None : False : False :  Reals
      6 :  None : -28.872348336757398 :  None : False : False :  Reals
      7 :  None : -14.039749134653078 :  None : False : False :  Reals
      8 :  None : -0.8474521090027167 :  None : False : False :  Reals
      9 :  None :   56.89430545783776 :  None : False : False :  Reals
     10 :  None :   285.5068982735597 :  None : False : False :  Reals
     11 :  None :   679.3838738157001 :  None : False : False :  Reals
     12 :  None : -20.230026149875016

In [10]:
# store the alpha
alpha = model.get_alpha()
alpha

array([-22.93593993, -22.98683384, -22.86388735,  33.46099119,
       -22.93846935, -17.75385609, -22.92087971, -17.79486514,
       -22.90330938, -17.87082458,  89.08424853,  90.86453838,
       -22.83513509, -17.80922926, 102.37881893, -17.67056838,
       -22.96502966, -22.91728954, -22.90726524, -17.68187113,
       -17.28913525, -21.14681741, -25.26657861, -17.63178583,
       -22.95778946, -22.84466087, -22.84627636,  33.46123681,
       -22.96408014, -17.80276177, -22.90810598, 104.32669023,
       -17.71133162, -17.7761864 , -19.65353389, -17.66671101,
       -17.7038659 , -22.96505005, -22.99035394, -17.62793049,
       -17.66132912, -22.99252479,  33.46170122, -22.92160801,
       -22.89385742, -22.94306226, -17.63677401, -22.99161198,
       -17.66632916,  33.45220523, -22.94244663, -17.70733908,
       -22.87523682, -17.6613982 , -22.91256809,  22.31186594,
       -14.38699188, -22.88258402, -22.09519356, -17.76759295,
       -24.5428972 ,  33.46135501, -17.62860774, -13.85

In [11]:
# store the beta
beta = model.get_beta()
beta

array([[1.35858457e-01, 1.12739842e-02],
       [1.36376623e-01, 1.09037868e-02],
       [1.35666983e-01, 1.13631431e-02],
       [1.32352137e-01, 2.11172062e-08],
       [1.47555584e-01, 1.91245813e-03],
       [1.34107237e-01, 8.10206675e-03],
       [1.35700439e-01, 1.14076128e-02],
       [1.34115326e-01, 8.12155036e-03],
       [1.35623787e-01, 1.14725926e-02],
       [1.34141258e-01, 8.16188266e-03],
       [1.16457955e-01, 1.47170839e-02],
       [1.29254412e-01, 1.59746567e-03],
       [1.35607720e-01, 1.13928799e-02],
       [1.34118368e-01, 8.13034495e-03],
       [1.10432229e-01, 2.15259855e-02],
       [1.34072053e-01, 8.08865311e-03],
       [1.35865066e-01, 1.13163935e-02],
       [1.35623836e-01, 1.15000205e-02],
       [1.35622831e-01, 1.14811282e-02],
       [1.34075666e-01, 8.09009011e-03],
       [1.45089380e-01, 1.66895208e-04],
       [1.42331259e-01, 4.47591842e-03],
       [1.34641777e-01, 3.42340489e-02],
       [1.34053281e-01, 8.09762097e-03],
       [1.357870

In [12]:
# store the residual
residual = model.get_residual()
residual

array([  -2.80240401,    1.41405281,  -22.22374489, -350.91097509,
        -13.69989994,  101.01484316,  -28.87234834,  -14.03974913,
         -0.84745211,   56.89430546,  285.50689827,  679.38387382,
        -20.23002615,  -70.00794   ,   10.50653029,   74.59733583,
         -6.53891638,  -30.07641267,  -40.13473761,  -27.77786744,
         48.75945801,   87.00800579,   22.48075618,   23.9507284 ,
         -2.1416654 ,  -22.83660478,  -37.86104821, -351.07094002,
         66.85759057,  -21.70281486,   -8.95128579,  216.00593129,
         37.59734005,  -31.81149601,  -23.78470876, -201.34125864,
        -69.29033394,    6.26876145,    3.75584188,  -74.60739791,
         -1.97479242,  -11.97087724, -236.7462774 ,    6.57458264,
         11.65688191,  -20.00399714,  -67.21455741,   -5.23911324,
        -55.94694781,  265.5141281 ,    1.92419887,  -17.65081814,
          4.65630352,   38.85434607,   -2.90330635,  349.52829711,
        163.99050232,   35.00136221,   28.39293601,  -99.13217